import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';



export const metadata: Metadata = {
  title: "Tertulia FEMSA ",
  description: "Generated by tertulia with NextJS",
};

export default function RootLayout({children,  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="BackFemsa">
        <Header />
        <main className="min-h-screen container mx-auto p-4 ">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
