import type { Metadata } from "next";
import "../styles/globals.css";
import HeaderWrapper from '../app/headerwrapper/headerwrapper';



export const metadata: Metadata = {
  title: "Tertulia FEMSA ",
  description: "Generated by tertulia with NextJS",
};

export default function RootLayout({children,  
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="es">
      <body className="BackFemsa">
        <HeaderWrapper />
        <main className="w-full min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
